name: Build Resume

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install pyyaml jinja2 marko requests
      - name: Run build
        run: python -c "from renderer import build; build()"
        working-directory: resume
      - name: Add .nojekyll
        run: touch output/.nojekyll
        working-directory: resume
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./resume/output
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4